### ISSUE TITLE
Layout collision when media query not activated, but width is constrained

### ISSUE THREAD

**Issue by Scotchester** [cfpb/cf-pagination#14]
## URL

http://cfpb.github.io/cf-pagination/docs/
## Actual Behavior

This occurs when the viewport width is not narrow enough to trigger the media query, but the pagination component's width is constrained, e.g., by a multi-column layout like the docs. The "Page" label is overlapped by the "Previous" button.
## Expected Behavior

The layout responds appropriately.
## Steps to Reproduce
1. Go to the URL given above.
2. Reduce viewport width to something between 768px and about 800px.
## Screenshot

![screen shot 2014-05-16 at 09 43 24](https://cloud.githubusercontent.com/assets/1044670/2997514/1ba2c2d0-dd00-11e3-9adc-42a20d20faf2.png)

**Comment by himedlooff** [comment]
This will be different depending on the usage. I wonder if we should set a `@pagination-bp` var so each project can set it's own breakpoint for this component.

**Comment by himedlooff** [comment]
@Scotchester what do you think of the `@pagination-bp` idea? I think that would solve this issue nicely.

**Comment by KimberlyMunoz** [comment]
@Scotchester. I think we have a pagination-bp. Did that get implemented to fix this issue?
