### ISSUE TITLE
Inconsistent abstraction of breakpoint values

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cf-pagination#27]
[`cf-pagination.less`](https://github.com/cfpb/cf-pagination/blob/gh-pages/src/cf-pagination.less) contains four breakpoints:

319px
320px
369px
640px

These are each used one time, but the last, 640px, in abstracted into the [`@pagination-bp`](https://github.com/cfpb/cf-pagination/blob/gh-pages/src/cf-pagination.less#L36) variable. (Used one time [here](https://github.com/cfpb/cf-pagination/blob/gh-pages/src/cf-pagination.less#L200).)

https://github.com/cfpb/cf-pagination/issues/14#issuecomment-43343727 suggests `@pagination-bp` is so projects can override the breakpoint value. Is there a design choice here to disallow overriding of the breakpoint values through a variable for the remaining three breakpoints?

cc @himedlooff

**Comment by himedlooff** [comment]
> Is there a design choice here to disallow overriding of the breakpoint values through a variable for the remaining three breakpoints?

No. We should have a variable for each. Although, I feel like we can combine 320/319 into one variable and do something like:

``` less
@pagination-bp-small: 320px;
@pagination-bp-small-min: @pagination-bp-icons;
@pagination-bp-small-max: @pagination-bp-icons - 1px;

@pagination-bp-icons: 369px;

@pagination-bp-large: 640px;
```

Then, when someone needs to override them they could override these following three variables

``` less
@pagination-bp-small
@pagination-bp-icons
@pagination-bp-large
```

We could also potentially ditch the breakpoint for icons and consolidate it somehow.

**Comment by anselmbradford** [comment]
There are a lot of occurrences in flapjack of breakpoints that are 1px under or 1px over. I did some preliminary thinking about how that might be consolidated. Like I might just want to specify the breakpoint and have a mixin that decrements or increments it by a pixel based on whether it's a min- or max- breakpoint value. Perhaps like:

``` less
.respond-to-min( min-bp(640px), ...
.respond-to-max( max-bp(640px), ...
```

Which ends up as:

``` css
@media only all and (min-width: 640px) {

...

@media only all and (max-width: 639px) {
```

(Note: for clarity I'm using pixels instead of ems just as a demo.)

In that case though, `min-bp()` isn't actually doing anything and is just there for clarity (and if a refactor shifted the pixel from max to min).

**Comment by jimmynotjim** [comment]
I feel like this is a approaching a land of diminishing returns. The example is almost as much typing as the full media query (even requiring two extra reaches for the `shift` key) and we'd be creating a new function to save subtracting a single digit. Creating `min-` and `max-` variables when appropriate seems a lot simpler.

**Comment by anselmbradford** [comment]
> I feel like this is a approaching a land of diminishing returns. The example is almost as much typing as the full media query (even requiring two extra reaches for the shift key) and we'd be creating a new function to save subtracting a single digit. Creating min- and max- variables when appropriate seems a lot simpler.

Haha, yeah, I agree, that was just preliminary thinking.
I'm not sure without looking into it further, but it appears in flapjack that in some cases the breakpoint value is decremented and sometimes it's incremented at the junction between min- and max- settings (for example, the breakpoints 767, 768, and 769). So I was thinking around how there might be a pattern that encourages consistency in adjusting the breakpoint value and also reduces variables like, e.g.:

@bp-min: 640px;
@bp-max: 639px;

Another option is to have `respond-to-max` decrement the breakpoint value by default unless told otherwise. Something like `.respond-to-max(@bp, @rules, @is-bp-boundary:true)`. Then you could hand the same breakpoint value to both `respond-to-min()` and `respond-to-max()` and they wouldn't overlap unless you explicitly told them to.

Anyway, back to beta release work for me :)

**Comment by himedlooff** [comment]
@anselmbradford, fun ideas! Not sure if they make things easier though. It seems simpler to just have a min and max variable for each breakpoint.
