### ISSUE TITLE
Weird right padding on number input

### ISSUE THREAD

**Issue by himedlooff** [cfpb/cf-pagination#3]
## URL

http://cfpb.github.io/cf-pagination/demo/
## Actual Behavior

There is no right padding on the input.
## Expected Behavior

It should have right padding. Also if you take away the `type="number"` the padding returns.
## Screenshot

![cf-pagination-android](https://f.cloud.github.com/assets/1093373/2314842/dcda2b60-a31b-11e3-9efd-6b0a66ee3c64.png)

**Comment by himedlooff** [comment]
I tried using `type="text" pattern="[0-9]*"` instead of `type="number"` and the padding issue goes away. By doing this we don't get the number dial pad on ios, we get the keyboard with numbers and a bunch of special characters. The saucelabs android emulator doesn't show the device keyboard so it's hard to tell if this affects the android keyboard. From what I'm reading online though it's hard to get it to use the number dial pad.

**Comment by himedlooff** [comment]
There seems to be some pushback on using `type=number` anyway (from UX and Design) since it adds tiny controls on desktops. I wonder if we should just use `type=text`.

**Comment by KimberlyMunoz** [comment]
Right now on flapjack, we're just using `type=number` and dealing with the pushback. We'll reopen if the design manual wants to bring it up again.
